# spring import
spring.config.import=optional:file:.env[.properties]

# DATABASE CONNECTION
spring.datasource.url=jdbc:mysql://${DB_PATH}?useSSL=false
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# DIALECT
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update