# spring import
spring.config.import=optional:file:.env[.properties]

spring.application.name=social-media
api.security.token.secret=${JWT_SECRET}
spring.profiles.active=test

# file propeties
file.upload-dir=${FILE_PATH}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=22MB